### PR TITLE
[IMIS] 3360 reference dto required UUID

### PR DESCRIPTION
**Pull request by JonasCir**
Ticks partially one box of #3360 
This fix makes the `uuid` fields of all reference DTOs required. -> this makes the `uuid` fields in the openAPI description required -> clients generated from this api spec validate automatically that uuids are set correctly in the request -> this solves (partially) my problem

Please note that this does not add any server side validation, providing empty `uuid` values in references still triggers an internal server error (500) and is not gracefully handled (i.e., 400). This is left as future work, but having this change included in the repo would tremendously help me to debug the API.

### CODE REVIEW

**Comment by JonasCir** [comment]
@syntakker somehow your commits ended up in my PR :D

**Comment by JonasCir** [comment]
Does not work for some reason

**Comment by JonasCir** [comment]
@MateStrysewske This is ready for review, please reassign at your discretion.

This PR indicates that `*ReferenceDtos` should carry an `uuid` property, at least on API level. This does not add any backend checks, providing empty references still blows up the resulting DB transaction as these fields are mapped as `NOT NULL`. However, this allows clients which are generated from the openAPI specs to check the invariants locally which makes development much more pleasant. 

Please also note, that simply adding `@Required ` to `ReferenceDto` wouldn't work. I rewrote the logic such that `@Required` on a field in a super class now gets reliable populated to sub classes. The changes introduced are the following:

1. Make `ReferenceDto.uuid` required
1. Move the annotation handling logic from `SormasSwaggerExtension ` to `AttributeConverter`
  1. The handling for `@Required ` was moved to `applyBeanValidatorAnnotations` (it's the same function which handles `@NotNull` and such)
  1. rest of `resolve` is the same, just the call to super was added

**Comment by MartinWahnschaffeSymeda** [comment]
@JonasCir Looks good to me and makes a lot of sense :-)
Also thanks a lot for cleaning up the code formatting and comments.

**Pull request merged**
