### PR TITLE
Introduce maven wrapper for local maven version

### PR DESCRIPTION
**Pull request by patryk-marcin-zielinski**
*Introduce mvn wrapper*
- It allows us to download the correct version of maven locally
- it allows us to run the project without having maven installed

### CODE REVIEW

**Comment by syntakker** [comment]
Although excluded in `.gitignore`, the file `.mvn/wrapper/maven-wrapper.jar` is added in your commit.

**Comment by patryk-marcin-zielinski** [comment]
> Although excluded in `.gitignore`, the file `.mvn/wrapper/maven-wrapper.jar` is added in your commit

Maybe the comment is misleading. it is excluded from being ignored.

**Comment by syntakker** [comment]
@patryk-marcin-zielinski Sorry, I indeed misread this :-)

**Comment by MartinWahnschaffeSymeda** [comment]
@patryk-marcin-zielinski Thanks a lot for this!

Can you provide a short guide on how to use this and add the steps to https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/DEVELOPMENT_ENVIRONMENT.md

I guess you have a specific use case in mind...

I'm also wondering whether we should really have the mvnw file in the project root are maybe better move it to sormas-base. Any thoughts on this?

**Comment by MichaelSp** [comment]
I've added the wrapper to my documentation PR #2866

It's best-practice to keep the wrapper in the root folder.

**Comment by JonasCir** [comment]
> Can you provide a short guide on how to use this and add the steps to https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/DEVELOPMENT_ENVIRONMENT.md

Done in PR #2866 :+1: 

> I'm also wondering whether we should really have the mvnw file in the project root are maybe better move it to sormas-base. Any thoughts on this?

See last comment of @MichaelSp :smiley:

@MartinWahnschaffeSymeda Can this PR and #2866 get a review? We have a new team member who has maven problems which I think could be mitigated by this PR.

**Comment by MartinWahnschaffeSymeda** [comment]
@MichaelSp @JonasCir Done. Thanks again for the PR. For #2866 I have requested some changes.

**Pull request merged**
