### PR TITLE
[#4635] Complete markdown linting of repo

### LINKED ISSUE #4635: Correct Remaining Markdown Linter Errors
# Add Github Actions Super-linter to SORMAS

## Feature Description

Post introduction of the super-linter, there are still a few markdown files which have yet to be brought into full compliance with markdownlint.

## Problem Description

Minor markdown linting issues.

## Proposed Change

Update markdown files as necessary.

## Possible Alternatives

Do nothing. :)

### PR DESCRIPTION
**Pull request by jeremiahpslewis**
Fixes #4635 by updating markdown files.

### CODE REVIEW

**Comment by jlewis91** [comment]
@JonasCir Started to work on bash, realized that some markdown files had not been included in the initial PR, this PR ensures all markdown files in current repo are validated and compliant :)

**Comment by JonasCir** [comment]
Hi thank you @jlewis91 !
I will likely do a full review at the beginning of next week. I have one request though: Could you remove the on push trigger for the linter? From my experience, most commits are pushed but nobody really looks at the intermediate CI results. So this will run quite often and I really want to avoid that GitHub CI de-prioritizes our job b/c of high request rate. I think we can save the CI time and just leave it on for PRs. In the most cases there are additions or change requests after the PR was opened so the lint errors can be easily included.

**Comment by JonasCir** [comment]
hmm or is this already the case by adding `workflow_dispatch`? B/c if you take a look at the passed checks, you only see Lint Code Base / Lint Code Base (pull_request) Successful in 3m (and on push as you can see here: https://github.com/hzi-braunschweig/SORMAS-Project/pull/4640)

**Comment by jlewis91** [comment]
@JonasCir Updated, on push is removed; workflow dispatch means that you can manually trigger a build via web interface.

**Comment by jlewis91** [comment]
Hi @JonasCir! Hope it's ok if I follow up with you here and check whether there is anything I could do to support getting this PR merged. Cheers, J

**Comment by JonasCir** [comment]
@jlewis91 This is completely on me, I'll do a review when I find time, sorry for the delay!

**Comment by jlewis91** [comment]
np, thanks for the update!

**Review by JonasCir — APPROVED** [review]
lgtm, thank you for contributing and your patience :rocket:

**Pull request merged**
