### PR TITLE
[IMIS] List case and contact counts in event overview #3276

### PR DESCRIPTION
**Pull request by DavidBaldsiefen**
This PR implements #3276 
It would be especially interesting to see how it performs on systems with a large database (many events & contacts)

Edit: #3562 is also implemented with this PR.

### CODE REVIEW

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
The approach taken in this PR will lead to massive performance problems because it requires two queries per list entry; one of those even involves multiple additional queries. The correct way to do this is to extend the selection in the getIndexList with counts.

**Comment by MateStrysewske** [comment]
The other option is to do two additional queries after the index list has been retrieved and build a map. That allows a more complex query, but still limits the amount of additional queries to two instead of two per shown event. There are quite a lot examples in the existing getIndexList methods for this approach.

**Comment by ftavin** [comment]
@Seal33 do you know when you will be able to adjust your PR ?

**Comment by Seal33** [comment]
@ftavin I am still on it, and I hope to do so this week.

**Comment by Seal33** [comment]
@bernardsilenou @ftavin @carolinverset

All the base functionalities of #3276 and #3562 are implemented now. I will still have to do some cleanup, but you could try out the changes already and tell me if they behave as expected (especially both calculation methods for contact counts)

**Comment by Seal33** [comment]
@carolinverset @bernardsilenou 
The PR is ready for merging now. I haven't been able to implement Sorting of the columns yet, as it is a little bit more complicated than one might think (see https://github.com/hzi-braunschweig/SORMAS-Project/issues/2016).
My suggestion would be to move that to another issue, so that we can make sure this PR will be merged for 1.53

Also, another remark would be that one might consider changing the column titles:
- "Participant Count" -> "Participants"
- "Case Count" -> "Cases"
- "Contacts among Participants" -> "Contacts"

This would improve the overall readability of the table. What do you think?

**Comment by Seal33** [comment]
Checks may fail after latest merge as current development branch fails tests.

**Comment by MateStrysewske** [comment]
@Seal33 Just a quick heads-up - reviewing this pull request will take a bit longer because we need to have a deeper look into the queries. We recently had serious performance problems that were caused by some subqueries and we'll have to make sure that we won't run into similar issues with the new subqueries introduced in this PR. It's definitely A LOT better than having an additional query per list entry, but we still need to analyse the performance impact.

**Comment by Seal33** [comment]
@MateStrysewske Thank you for the headsup! Yes, take your time. The performance impact would be especially interesting on systems with large Contact and Event databases.

It would be really nice if this PR would be merged for 1.53

**Comment by MateStrysewske** [comment]
@Seal33 The query that this code results in will very likely have a very negative impact on performance; not necessarily in the directory because that's lazy-loaded by default, but at least for the export. We need a different solution for this. One approach could be to collect the information after the initial query with one (or more) additional queries, as it's done e.g. in the detailed case export. This would result in more than one query, but those queries would ideally be more lightweight and therefore have a less negative impact on performance overall. If you find a different solution, that would also be fine.

This is the resulting query:

```
  select 
  event0_.uuid as col_0_0_, 
  event0_.eventStatus as col_1_0_, 
  event0_.eventInvestigationStatus as col_2_0_, 
  
  (select count(eventparti7_.id) 
  from EventParticipant eventparti7_ 
  where eventparti7_.event_id=event0_.id and eventparti7_.deleted=false) as col_3_0_, 
  
  (select count(eventparti8_.id) 
  from EventParticipant eventparti8_ 
  where eventparti8_.event_id=event0_.id and eventparti8_.deleted=false and (eventparti8_.resultingCase_id is not null)) as col_4_0_, 
  
  (select count(eventparti9_.id) 
  from EventParticipant eventparti9_ 
  left outer join cases case10_ on eventparti9_.resultingCase_id=case10_.id 
  where eventparti9_.event_id=event0_.id and eventparti9_.deleted=false and (eventparti9_.resultingCase_id is not null) and case10_.outcome=?) as col_5_0_, 
  
  (select count(eventparti11_.id) 
  from EventParticipant eventparti11_ 
  inner join Person person12_ on eventparti11_.person_id=person12_.id 
  inner join Contact contacts13_ on person12_.id=contacts13_.person_id 
  where eventparti11_.event_id=event0_.id and eventparti11_.deleted=false and contacts13_.deleted=false) as col_6_0_, 
  
  (select count(contact14_.id) 
  from Contact contact14_ 
  inner join Person person15_ on contact14_.person_id=person15_.id 
  inner join EventParticipant eventparti16_ on person15_.id=eventparti16_.person_id 
  inner join cases case17_ on contact14_.caze_id=case17_.id 
  inner join EventParticipant eventparti18_ on case17_.id=eventparti18_.resultingCase_id 
  where contact14_.deleted=false and eventparti16_.deleted=false and eventparti16_.event_id=event0_.id and eventparti18_.event_id=event0_.id) as col_7_0_, 
  
  event0_.disease as col_8_0_, 
  event0_.diseaseDetails as col_9_0_, 
  event0_.startDate as col_10_0_, 
  event0_.endDate as col_11_0_, 
  event0_.eventTitle as col_12_0_, 
  region2_.uuid as col_13_0_,
  region2_.name as col_14_0_, 
  district3_.uuid as col_15_0_, 
  district3_.name as col_16_0_, 
  community4_.uuid as col_17_0_, 
  community4_.name as col_18_0_, 
  location1_.city as col_19_0_, 
  location1_.street as col_20_0_, 
  location1_.houseNumber as col_21_0_, 
  location1_.additionalInformation as col_22_0_, 
  event0_.srcType as col_23_0_, 
  event0_.srcFirstName as col_24_0_, 
  event0_.srcLastName as col_25_0_, 
  event0_.srcTelNo as col_26_0_, 
  event0_.srcMediaWebsite as col_27_0_, 
  event0_.srcMediaName as col_28_0_, 
  event0_.reportDateTime as col_29_0_,
  user5_.uuid as col_30_0_, 
  user6_.uuid as col_31_0_ 
  
  from events event0_ 
  left outer join Location location1_ on event0_.eventLocation_id=location1_.id 
  left outer join Region region2_ on location1_.region_id=region2_.id 
  left outer join District district3_ on location1_.district_id=district3_.id 
  left outer join Community community4_ on location1_.community_id=community4_.id 
  left outer join users user5_ on event0_.reportingUser_id=user5_.id 
  left outer join users user6_ on event0_.surveillanceOfficer_id=user6_.id 
  
  where (event0_.archived=? or event0_.archived is null) and event0_.deleted=? order by event0_.changeDate desc limit ?]]
```

And this is a screenshot of the query analysis which visualises how the result is built:

query_analysis

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
See comment above

**Comment by Seal33** [comment]
Thank you for the review! I've just now seen a lot of groundwork has been done in parallel with #3035 (PR #3344 )

That means there is now a lot of duplicate code in my approach. I will try to find a solution that uses the changes implemented with PR #3344 ASAP so that the code and approach is more uniform.

**Comment by Seal33** [comment]
@MateStrysewske 
I have moved the calculations to a separate query as asked. However I can not really guarantee or tell if the performance increase would be significant enough. Do we have a test system with demo event-data somewhere?

**Comment by MateStrysewske** [comment]
@Seal33 The new implementation doesn't solve the issue, but basically only shifts it to another place. It's still multiple subqueries with multiple FROMs (most of them using the same table) that will result in a very very complex query that will probably take a lot of time to run through. That's why my suggestion was to move this to individual queries that might be simpler.

However, since these changes have the potential to slow down the system, I'd like to postpone it to the next release (given that we have feature freeze today). We were pretty busy with the hotfix this sprint which is why it took me so long to pick up the review of this PR again, so I'm really sorry for that because we could've otherwise made sure that it can be pushed to this release.

Is that okay for you anyway?

**Comment by Seal33** [comment]
@MateStrysewske Thank you for the quick review, I already thought so. However, I've based my solution on the present approaches in CaseFacadeEjb and EventParticipantEjb.

Could you tell me how/where you created the query analysis from your comment above? Would it help in any way if I move the subqueries into complete standalone-queries, or does that not change a thing as the queries themselves stay the same?

For me it's fine if this PR get's pushed back, however I am not the consumer of this product ;)

Another thing I could offer is create a reduced PR today which just includes the Case and Death Count queries. Those are less complex than the contact queries, and would already offer some value to the health offices. What do you think?

**Comment by MateStrysewske** [comment]
@Seal33 Yeah, that's a possibility, similar to e.g. the EventSummaryInformation in the case export. 

I created the query analysis in pgAdmin. It definitely helps to check whether an individual query is way too complex. I'm no database expert myself though, so I don't know for sure that moving the subqueries to individual queries will help, but I guess it definitely won't make the matter worse. :)

That would be fine by me, yes!

**Comment by Seal33** [comment]
@MateStrysewske I've created PR #3760 , which is essentially this PR reduced to case and death count queries.
The queries themselves are unchanged, however they should be light enough performance-wise.

It would be really great if #3670 can still be merged for 1.53.
Functionality-Wise the PR works as far as I could test it, and all tests passed locally.

Meanwhile, I will try and find a way to calculate the contact counts more efficiently, so that the full feature can finally be implemented for 1.54. If I find a better way I will also adjust the calculation methods for Participant, Case and Deathcount accordingly, too.

**Comment by Seal33** [comment]
@MateStrysewske 

I think i found a much better query which should be massively better for performance. However, while it works flawlessly in pgAdmin, I simply cannot get it to work in the code. Could you tell me how you were able to extract the generated query from the code above?

**Comment by MateStrysewske** [comment]
@Seal33 Open the persistence.xml in sormas-backend and set the property `hibernate.show_sql` to true; that will print every query that's performed to the console.

**Comment by DavidBaldsiefen** [comment]
Closed in favor of #3981 .

**Pull request closed without merging**
