### PR TITLE
add dependency review action

### LINKED ISSUE #11658: Use dependency review action [0.5]
### Problem Description
We do not have a mechanism which prevents insecure dependencies from flowing in into our code base. We want to be able to reliable audit new dependencies to catch security risk as early as possible.

### Proposed Solution
Use the [dependency-review-action](https://github.com/actions/dependency-review-action#readme) developed by GitHub to stop the described problem from occurring in the future.

### Possible Alternatives
None, we should really take care of this.

### Additional Information
[here](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review) and [here](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-dependency-review).

### PR DESCRIPTION
**Pull request by JonasCir**
Fixes #11658

This action can also check for licenses of dependencies. I do not now if there were discussions with the foundation or someone else to monitor licenses for compliance.

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11660

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11660

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11660

**Review by StefanKock — APPROVED** [review]
Discussed with @MartinWahnschaffe and approved. The dependency to prove how this works is removed.

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11660

**Pull request merged**
