### PR TITLE
fix maven warnings

### LINKED ISSUE #2583: fix some maven warnings
#### Proposed Change
Maven has some warnings

 * The artifact org.hibernate:hibernate-validator:jar:6.1.5.Final has been relocated to org.hibernate.validator:hibernate-validator:jar:6.1.5.Final
 * maven-javadoc-plugin additionalparam -> additionalJOption
 * The project uses prerequisites which is only intended for maven-plugin projects
 * suppress MavenModelInspection warnings

### PR DESCRIPTION
**Pull request by MichaelSp**
Some maven warnings are fixed in this PR
 * [x]  The artifact org.hibernate:hibernate-validator:jar:6.1.5.Final has been relocated to org.hibernate.validator:hibernate-validator:jar:6.1.5.Final
 * [x] maven-javadoc-plugin additionalparam -> additionalJOption 
 * [x] The project uses prerequisites which is only intended for maven-plugin projects
 * [x] suppress MavenModelInspection warnings 
 * [x] formatting
 * [x] make test-log more readable 

fixes #2583

### CODE REVIEW

**Comment by MateStrysewskeSym** [comment]
@MichaelSp Thanks for your contribution! Please make sure to open an issue in our repository and link your pull request to it.

**Comment by MichaelSp** [comment]
I can't reproduce the test failure here locally:
```
de.symeda.sormas.api.utils.OutdatedEntityException: EpiDataDto is older than current version on server: 'TOJ5Z6-3MAJQX-IOVUZI-OHLBKBOE'

	at de.symeda.sormas.backend.contact.ContactServiceTest.testGetAllRelevantContacts(ContactServiceTest.java:122)
```

Any idea? Is that a known issue?

**Comment by MateStrysewskeSym** [comment]
@MichaelSp You can ignore it, it's a timing issue in Java. We probably have to add manual timeouts to these unit tests to make sure that they run through.

**Comment by MichaelSp** [comment]
@MateStrysewskeSym I think I found a fix for the flaky tests

**Comment by StefanKock** [comment]
I have two issues with this pull request:
1. The commits do not contain the corresponding ticket ID
2. The workaround for #2552 should not go into development (or at least with that ticket ID)

**Comment by MichaelSp** [comment]
Oh, I didn't know there is already a ticket for that. I've extracted it into a separate PR: https://github.com/hzi-braunschweig/SORMAS-Project/pull/2589

**Comment by MartinWahnschaffeSymeda** [comment]
@MichaelSp Changes overall now look good, but travis-ci seems to have a problem now:

> The command "mvn test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn" failed and exited with 1 during .

**Comment by JonasCir** [comment]
```
testGetAllRelevantContacts(de.symeda.sormas.backend.contact.ContactServiceTest)``  Time elapsed: 3.013 sec  <<< ERROR!

de.symeda.sormas.api.utils.OutdatedEntityException: EpiDataDto is older than current version on server: 'TOJ5Z6-3MAJQX-IOVUZI-OHLBKBOE'

	at de.symeda.sormas.backend.contact.ContactServiceTest.testGetAllRelevantContacts(ContactServiceTest.java:122)
```
I encountered a similar test failure, but it is flaky for me. Maybe just restart the CI? :D

**Comment by MichaelSp** [comment]
@MartinWahnschaffeSymeda  I've extracted the fix for flaky tests as per @StefanKock 's request. That's why the tests are failing again more often than not.

**Comment by MartinWahnschaffeSymeda** [comment]
@MichaelSp Ah, sorry - my bad. Merged now.

**Pull request merged**
