### PR TITLE
SORDEV-9470

### PR DESCRIPTION
**Pull request by pk-sgent**
SORDEV-9470 #

### CODE REVIEW

**Comment by pk-sgent** [comment]
image

**Comment by pk-sgent** [comment]
image

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: Please find the results at https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11461

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: Please find the results at https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11461

**Pull request merged**
