### PR TITLE
[DRAFT] Make generated Properties sortable (#3772)

### PR DESCRIPTION
**Pull request by DavidBaldsiefen**
This PR implements #3772

### CODE REVIEW

**Comment by Seal33** [comment]
@MateStrysewske I have implemented one possible solution to make generated properties (such as case and deathcount for events) sortable. For this I just used Collections.sort on the generated indexList before returning, which worked quite well.

It would be really nice if you could look at this solution and give me some feedback. If it's fine by you, I can then go and implement this in several other places (e.g. case grid)

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen I guess this doesn't really work because of lazy loading, because it will only sort the sublist of data that is currently returned, and that will result in a false sorting overall. @HolgerReiseVSys @StefanKock @MartinWahnschaffe Can you correct me if I'm wrong? You only have to look at the first commit in this PR

**Comment by MartinWahnschaffe** [comment]
@MateStrysewske Your are right. It won't work that way. The sorting has to be applied in the SQL statement, otherwise it can't work with lazy loading.

**Comment by DavidBaldsiefen** [comment]
> @MateStrysewske Your are right. It won't work that way. The sorting has to be applied in the SQL statement, otherwise it can't work with lazy loading.

In that case I don't see any way to make those properties sortable, as they are fetched in completely different queries and then attached to the already sorted result set of the main query. Or do you have any other idea?

**Pull request closed without merging**
