### PR TITLE
fix some typos and replace SORMAS-Open with SORMAS-Project in docs

### PR DESCRIPTION
**Pull request by obdulia-losantos**
- Replaced `SORMAS-Open` with `SORMAS-Project`
- Fixed some typos in the docs.
- Replaced spaces with tabs in some `pom.xml` files for clarity.

### CODE REVIEW

**Comment by MateStrysewske** [comment]
@obdulia-losantos Hey! Sorry that we couldn't respond to your PR until now. Your contribution is very welcome. Unfortunately, there are a few merge conflicts by now - would you still be available to solve those?

**Comment by obdulia-losantos** [comment]
Yes, of course. But now it's me who is on holidays...

**Comment by obdulia-losantos** [comment]
@MateStrysewske conflicts resolved!

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
Looks like there are build problems after your changes, so there seems to be something off. Can you have a look at that and try to fix them?

**Comment by obdulia-losantos** [comment]
Linter errors:

image

File changes:

image

@MateStrysewske I don't know how to proceed, the linter errors are on lines that I didn't touch at all...

**Comment by MateStrysewske** [comment]
@JonasCir Do you have an idea what could be wrong here?

**Comment by JonasCir** [comment]
@MateStrysewske What is going on here is intended behavior of GitHub. See [here](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)

You can just go ahead an click on Approve and run if you want to execute the CI :)

**Comment by MateStrysewske** [comment]
@JonasCir Sorry, the build error went away after the merge commit. Can you have another look at it, please?

**Comment by obdulia-losantos** [comment]
OK, I have changed the `CONTRIBUTING.md` file based on the linter errors. Could you re-run the tests? If it works then I'll try to change also the `external_visitis_API.yaml` file. @MateStrysewske

**Comment by MateStrysewske** [comment]
@obdulia-losantos Looks like it worked for CONTRIBUTING.md :)

**Comment by obdulia-losantos** [comment]
Continue with the rest...

**Comment by obdulia-losantos** [comment]
OK, I fixed the rest of markdown files, could you try again?

**Comment by obdulia-losantos** [comment]
@MateStrysewske I also ran the YAML linter tests locally and they passed!

**Review by MateStrysewske — APPROVED** [review]

**Comment by MateStrysewske** [comment]
Thank you! I'll merge the pull request after our next minor release (because we'll otherwise run into merge conflicts there because of the changes to the POM files).

**Comment by obdulia-losantos** [comment]
Thanks!

**Comment by JonasCir** [comment]
@obdulia-losantos Regarding the changes to `openapi` folder:Everything inside it is autogenerated by the CI so it will be overwritten by the next CI run on development. I'm afraid fixing the layout will not be easily possible, but the typos you found can be fixed in code I guess :)

**Comment by obdulia-losantos** [comment]
:joy:

**Comment by JonasCir** [comment]
The typos you fixed are caused by the typos in the corresponding annotation in code, so best is to `grep` for the typo see where it comes from and fix it there :D

**Comment by JonasCir** [comment]
And another small request: Since you are editing the README anyway: Add a section about https://hzi-braunschweig.github.io/SORMAS-Project/ as well and tell people it exists :) I would really appreciate it!

**Comment by obdulia-losantos** [comment]
@MateStrysewske I found the typos in the code and fixed them.

@JonasCir regarding you last request...

https://github.com/hzi-braunschweig/SORMAS-Project#guidelines-and-resources

> If you want to learn more about the development and contribution process, setting up or customizing your own system, or technical details, please consider the following guides and resources available in this repository. You can also view this readme and all guides outside the Wiki with a full table of content and search functionality here: https://hzi-braunschweig.github.io/SORMAS-Project/

**Comment by JonasCir** [comment]
Awesome thank you!

**Pull request merged**
