### PR TITLE
#2233: Follow-up end change triggers change request

### PR DESCRIPTION
**Pull request by ChristopherRiedel**

### CODE REVIEW

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
The popup that asks the user to change the quarantine end date only pops up AFTER the case has been saved. If the user clicks "Yes", the change is never actually saved. Everytime the user navigates back to the case afterwards (probably also when "No" is selected), the dialog pops up again immediately.

**Comment by ChristopherRiedel** [comment]
> The popup that asks the user to change the quarantine end date only pops up AFTER the case has been saved. If the user clicks "Yes", the change is never actually saved. Everytime the user navigates back to the case afterwards (probably also when "No" is selected), the dialog pops up again immediately.

Thats just not true.

**Comment by a-bakcsy-she** [comment]
Verified this on SORMAS Version: 1.48.0-SNAPSHOT

It is NOT reproducible. 
The pop-up is displayed immediately after the user changes the end date. 
Clicking on No does not save any changes, as well, clicking on Yes and afterwards on Discard reverts all changes.

**Comment by vlad-ciucescu** [comment]
Also checked and cannot reproduce. I got the same results as Andy.

**Review by vlad-ciucescu — APPROVED** [review]

**Pull request merged**
