### PR TITLE
#11568 documentation on how to do backend unit testing

### LINKED ISSUE #11568: Write documentation on how to do backend unit testing [1]
### Problem Description
Testing in sormas-backend is using multiple different frameworks and comes with some standard patterns. There is currently no documentation on how to use this.

### Proposed Solution
Create a readme in sormas-backend/srv/test that explains/lists:

- [x] ArchUnit
- [x] Junit 5 + Mockito
- [x] H2, testcontainers
- [x] Jakarate EE testing: cdi-test, transaction handling

### PR DESCRIPTION
**Pull request by MartinWahnschaffe**
Fixes #11568

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11577

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11577

**Review by StefanKock — CHANGES_REQUESTED** [review]

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11577

**Review by StefanKock — APPROVED** [review]
I approve the changes, but there is a finding concerning formatting to be fixed.

I vote for squash merge this PR.

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11577

**Pull request merged**
