### PR TITLE
#7647 [DEMIS2SORMAS] Introduce a messages content search field

### LINKED ISSUE #7647: [DEMIS2SORMAS] Introduce a messages content search field [3]
### Problem Description

Currently, it is not possible to search any content of a lab message from the message (lab and physician reports) directory. However, one downside of DEMIS messages is that most of the contents are not fixed values but strings. Being able to search the lab message details would enable users to e.g. look for specific substrings and find respective messages more easily. This is for example the case when searching for specific variants.

### Proposed Change

- [x] Introduce a search field for the lab message content which upon applying the filters searches for matching strings/substrings in `LabMessage.LabMessageDetails` and displays only the lab messages where the search input matches any content either completely or partially.

Mockup:
Lab message content search

### Implementation Details

- [x] Investigate possible performance issues (wildcards, minimum length of search string)
- [x] Create relevant amount of test data (10k plus)
- [ ] The user could limit the number by adding more filters
- [x] Implement search => show results without highligthing the search string

**If performance issues are expected:**
- [ ] Add a warning if the number of items to be searched exceeds x
- [ ] Add feature configuration 

### Additional Information

To consider: performance implications due to lengthy messages
No similarity/fuzzy search

### PR DESCRIPTION
**Pull request by leventegal-she**
Fixes #7647

Added explanation on the issue https://github.com/hzi-braunschweig/SORMAS-Project/issues/7647#issuecomment-1494096927

### CODE REVIEW

**Review by ChristopherRiedel — APPROVED** [review]
Besides the failing tests everything looks good

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11776

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
Can only look at the code and not test it; code looks good, however, build pipeline still fails because of linting.

**Comment by leventegal-she** [comment]
> Can only look at the code and not test it; code looks good, however, build pipeline still fails because of linting.

The lint is related to sql: No dialect was specified. Looks to be a configuration issue of the linter

**Review by MateStrysewske — APPROVED** [review]

**Pull request merged**
