### PR TITLE
Qu auto/sorqa 948

### PR DESCRIPTION
**Pull request by mk-sgent**
Changed selector "deleteUndelete" to "deleteRestore" for all occurrence in project

### CODE REVIEW

**Review by hms-sgent — APPROVED** [review]

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11884

**Comment by mk-sgent** [comment]
Jenkins tests results:
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/2663/allure/#packages/34cc6b3483abb58e3dc0220d10bc290d/14e8267ecec6090/

image

https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/2664/allure/#packages/7ab887922234243abaa93f1df67748c0/73caca7d7d1983c9/

image

https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/2665/allure/#packages/cc5b8d8c186189cd90612b28c77a9af4/c6b3716c4ae12b6a/

image

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11884

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11884

**Pull request merged**
