### PR TITLE
#3479 add setting to disable audit log of properties

### PR DESCRIPTION
**Pull request by ssferrazza**
See #3479

### CODE REVIEW

**Review by leventegal-she — APPROVED** [review]

**Review by StefanKock — CHANGES_REQUESTED** [review]
In sormas.properties this config flag is not defined.

```
# Turn off Attribute logging in the Auditlog on instances where this is not needed
# auditor.attribute.logging=true
```

**Review by StefanKock — COMMENTED** [review]
Is there a new line after 204? If not please add one, then it's fine

**Comment by ssferrazza** [comment]
> Is there a new line after 204? If not please add one, then it's fine
No, but I'll add it below the last line/property

**Review by StefanKock — APPROVED** [review]

**Comment by StefanKock** [comment]
@ssferrazza can you squash the changes when merging? I think the history is too fine grained now.

**Comment by ssferrazza** [comment]
@StefanKock Yes, I agree. I'll squash the changes when the CI is completed.

**Pull request merged**
