### PR TITLE
5901 update keycloak

### LINKED ISSUE #5901: Update to Keycloak 16
### Problem Description
Update to Keycloak 15.0.2. See https://www.keycloak.org/2021/08/keycloak-1502-released.html
Previously released:
* 16 https://www.keycloak.org/2021/12/keycloak-1600-released.html
* 15 https://www.keycloak.org/2021/12/keycloak-1510-released.html
* 14 https://www.keycloak.org/2021/06/keycloak-1400-released.html
* 13 https://www.keycloak.org/2021/05/keycloak-1300-released.html

Release note history: https://www.keycloak.org/docs/latest/release_notes/index.html

### Proposed Change
1. Update maven dependencies concerning Keycloak
2. Make sure the SORMAS Login theme is still compatible with version 15
3. Make sure the passwords for users are still updated correctly
4. Push relevant changes to SORMAS-Docker for update to Keycloak 15.
5. Update documentations for [SERVER_SETUP](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/docs/SERVER_SETUP.md#keycloak-server) and [SERVER_UPDATE](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/docs/SERVER_UPDATE.md#updating-keycloak)
6. Also deactivate the `login` page when Keycloak is configured as authentication provider

### PR DESCRIPTION
**Pull request by vidi42**
Fixes #5901

Has to be merged at the same time with https://github.com/hzi-braunschweig/SORMAS-Docker/pull/321

Changes:
* keycloak dependency version update
* sormas login theme updated
* documentation updated
* fixed bug where if the username of an user was updated, a duplicate was created in Keycloak
* deactivated the legacy login page when keycloak is active

### CODE REVIEW

**Comment by JonasCir** [comment]
Ok I'm experiencing a super strange behavior here:
When I navigate to `http://localhost:6080/sormas-ui/login` I get the following error message:

`DefaultOpenIdAuthenticationDefinition$1 does not define or inherit an implementation of the resolved method 'abstract java.lang.String endSessionEndpoint()' of interface fish.payara.security.annotations.OpenIdProviderMetadata.
at fish.payara.security.openid.controller.ConfigurationController.buildConfig(ConfigurationController.java:157) `

Here comes the interesting part:
In `payara-api-5.2020.jar` the annotation `fish.payara.security.annotations.OpenIdProviderMetadata` does NOT have an `endSessionEndpoint` method while `OpenIdProviderMetadata` in `security-connector-oidc-client-1.1.0.jar` has this method. It seams that the annotation is loaded from the wrong package?

**Comment by vidi42** [comment]
> Ok I'm experiencing a super strange behavior here: When I navigate to `http://localhost:6080/sormas-ui/login` I get the following error message:
> 
> `DefaultOpenIdAuthenticationDefinition$1 does not define or inherit an implementation of the resolved method 'abstract java.lang.String endSessionEndpoint()' of interface fish.payara.security.annotations.OpenIdProviderMetadata. at fish.payara.security.openid.controller.ConfigurationController.buildConfig(ConfigurationController.java:157) `
> 
> Here comes the interesting part: In `payara-api-5.2020.jar` the annotation `fish.payara.security.annotations.OpenIdProviderMetadata` does NOT have an `endSessionEndpoint` method while `OpenIdProviderMetadata` in `security-connector-oidc-client-1.1.0.jar` has this method. It seams that the annotation is loaded from the wrong package?

This should be solved starting with payara 5.2020.2 and is addressed in https://github.com/hzi-braunschweig/SORMAS-Project/pull/7570

**Comment by JonasCir** [comment]
See [comment](https://github.com/hzi-braunschweig/SORMAS-Docker/pull/321#issuecomment-1006444665) in SORMAS-Docker.

**Comment by JonasCir** [comment]
My biggest concern right now is that payara answers with 403 Forbidden, however, I do not see anything in the application logs. I'm investigating...

**Review by JonasCir — APPROVED** [review]
lgtm thanks @vidi42 for the work here!

**Pull request merged**
