### PR TITLE
1671: Provide Swagger documentation for sormas-rest

### PR DESCRIPTION
**Pull request by jabrandes**
This pull request adds the [`swagger-maven-plugin`](https://github.com/openapi-tools/swagger-maven-plugin) to the build process of `sormas-rest` module, such that [OpenAPI](https://swagger.io/specification/) specification files are generated during normal build procedure (`sormas-rest/target/swagger.{json,yaml}`). 

The specification files generated can be used for generating visual API documentation for the SORMAS REST interface, as well as for generation of API client stubs. See <https://editor.swagger.io/> for such functionality.

### CODE REVIEW

**Comment by StefanKock** [comment]
The changes look good and thought through. But all new dependencies have to be registered in _sormas-base/pom.xml_ in `dependencyManagement` and `build/pluginManagement`. At least the following config has to be moved there:
```
<groupId>...</groupId>
<artifactId>...</artifactId>
<version>...</version>
```

**Comment by jabrandes** [comment]
@StefanKock Thank you for your feedback. I have just got the minor question, whether the version of the `javax.security.enterprise-api` artifact has to be moved to `sormas-base` too, since it has been in the original `sormas-rest/pom.xml` when I branched off.

**Comment by StefanKock** [comment]
Yes indeed, it would be a good cleanup to move the version and scope to the `dependency management` in sormas-base.

**Comment by jabrandes** [comment]
@StefanKock, the requested changes should be in the latest commit.

**Comment by MateStrysewskeSym** [comment]
@jabrandes Thanks for your contribution!

**Pull request merged**
