### PR TITLE
#1863 app-barcode-feature

### PR DESCRIPTION
**Pull request by opatajoshua**
scan barcode to view sample
scan barcode to load lab sample id

### CODE REVIEW

**Comment by faatihi** [comment]
#1863

**Comment by bernardsilenou** [comment]
@faatihi Can you please explain how this implemented? Did you add a field in the case and sample to record the bar code?? 
This code is a good idea since it will serve as a unique identifier of the sample, Right?
Will users continue to annotate the sample using the EPID number of the case?

**Comment by MateStrysewskeSym** [comment]
@faatihi @opatajoshua The barcode scanner library you're using hasn't been updated for more than a year. We'll have to discuss whether we want such a dependency in SORMAS. Martin and I will discuss this on Monday.

**Comment by opatajoshua** [comment]
> @faatihi @opatajoshua The barcode scanner library you're using hasn't been updated for more than a year. We'll have to discuss whether we want such a dependency in SORMAS. Martin and I will discuss this on Monday.

Alright. 
Will "Google Vision" be a good alternative?

**Comment by MateStrysewskeSym** [comment]
@opatajoshua Can't decide that on my own, we'll discuss it as early as possible next week.

**Comment by opatajoshua** [comment]
This is another alternative: 
https://github.com/journeyapps/zxing-android-embedded.

GCNet wants the changes implemented as soon as possible so i need to make the necessary changes you recommend.

**Comment by faatihi** [comment]
> @faatihi Can you please explain how this implemented? Did you add a field in the case and sample to record the bar code??
> This code is a good idea since it will serve as a unique identifier of the sample, Right?
> Will users continue to annotate the sample using the EPID number of the case?

@bernardsilenou Initially, we used the labSampleID but realized it's only available to lab users. We've therefore added a new field, fieldSampleID.
There's going to be two identifiers now. fieldSampleID is entered by sample collectors for lab users to easily find whilst labSampleID is used for its originally intended purpose.

**Comment by bernardsilenou** [comment]
@faatihi  This means that we need to add a filter to search samples by the fieldSampleID
The fieldSampleID now is somehow replacing  the initial tacking of samples with EPDI number of the associated case. I think having a field sample ID is more important than tacking the sample with the EPID number of that case because:
1, Th epid number of a case can be edited in SORMAS after the sample has already been shipped to the lab. This will lead to errors.
2, Contacts with samples sent to lab are not registered as cases and will not have epid numbers.

For searching the DB, we should always use the feildSampleID the suppose?

**Comment by MartinWahnschaffeSymeda** [comment]
When you open the camera and then go back with the android back navigation you receive this error:

    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=74537, result=0, data=null} to activity {de.symeda.sormas.app.debug/de.symeda.sormas.app.sample.edit.SampleNewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4053)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4096)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
        at de.symeda.sormas.app.sample.edit.SampleEditFragment.onActivityResult(SampleEditFragment.java:292)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)
        at android.app.Activity.dispatchActivityResult(Activity.java:6915)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4049)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4096) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by MartinWahnschaffeSymeda** [comment]
I have fixed the issue and merged it.

**Pull request merged**
