### PR TITLE
Added personAddress field to both add and edit forms of Case and Contact

### PR DESCRIPTION
**Pull request by opatajoshua**
#1948

### CODE REVIEW

**Comment by MateStrysewskeSym** [comment]
@opatajoshua Adding the person address to the case or contact form doesn't seem like a good idea to me. The case and contact are semantically different from the person. We'll discuss this with the HZI in our review next week.

**Comment by faatihi** [comment]
@MateStrysewskeSym what was the outcome of the meeting?
The reason for this change is to help officers enter the coordinates.
What happens now is, officers only focus on the first page of the form.
Once they're done with the first page, they do not pay much attention to subsequent pages.
For that reason, we want the most important fields on the first page.

I think its a user-friendly approach to have important fields on the first page, irrespective of the entities those fields belong.

**Comment by MateStrysewskeSym** [comment]
@faatihi I honestly think this is a matter of training. It's basically impossible to fit all important fields into the first page (you could assume that symptoms, for example, are also very important), and the danger of mixing up the case jurisdictions with the person's home address is too big in this case. Users already have problems distinguishing cases and persons because they often think they're the same. This doesn't really make it better.

Unfortunately I didn't have a chance to talk to @bernardsilenou yet, but maybe he can have a quick look at our discussion here and let us know his opinion. The proposed change is that the person's address is added to the case data and contact data pages (for the reasoning see the comment by @faatihi, for my concerns see what I've written above).

**Comment by bernardsilenou** [comment]
@All,
I also think this is a matter of training. Adding person information to the cases and contacts will also distort structure of the system.

**Comment by faatihi** [comment]
OK. We'll drop this and work on adding the person address to case completeness calculation, as suggested by @bernardsilenou

**Pull request closed without merging**
