### PR TITLE
#4050 Fix FileReader compilation issue for java versions earlier than 11

### LINKED ISSUE #4050: umlauts and country variables produce errors during imports
### Bug Description
When using umlauts in free text fields in the import templates a critical error appears upon importing the data. This is quite problematic since the reason of the error is not easily identifiable and users rely more and more on the import function with rising case numbers. Furthermore, importing the newly added person.birthCountry and person.citizenship variables results in a partially failed import with only a generic error message also.

Applicable across all import options.
### Steps to Reproduce 
1. import data with either umlauts being entered in text type fields and country variables in the birthCountry and citizenship fields.
2. check errors upon importing the data.

### Expected Behavior
umlauts in text type fields should be ignored during the import and importing birthCountry and citizenship fields should be able to do with country infrastructure data as variables.
### Screenshots
Sorry for the german error messages. They didn't change when switching languages.
criticalErrorFreeTextUmlauts

umlauts:
"Import failed! Import failed because of a critical error. Please contact your admin..."

importFailBirthcountryCitizenship

birthCountry, citizenship:
"Import partially successful! The import was partially successful but some of the data could not be imported due to erroneous data."

### System Details
* Device:
* SORMAS version: 1.53.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information

### PR DESCRIPTION
**Pull request by vidi42**
Fixes #4050

### CODE REVIEW

**Comment by StefanKock** [comment]
SORMAS does not support JDK lower than 11 see [here](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_SETUP.md), why is this an issue?

**Comment by vidi42** [comment]
In that case we need to adjust the Nightly builds which seem to be using JDK 8

**Comment by StefanKock** [comment]
Maybe I was too quick: Since we need to support Java 7 on Android and this is part of sormas-api, the change is likely be needed / consistent.

**Comment by StefanKock** [comment]
To which ticket relates this (missing ticket Id in commit)

**Comment by syntakker** [comment]
It relates to issue #4050.

**Review by syntakker — APPROVED** [review]

**Pull request merged**
