### PR TITLE
Fusion doublon

### PR DESCRIPTION
**Pull request by zinebIdl**

### CODE REVIEW

**Comment by MateStrysewske** [comment]
Hey! What's the issue number associated with this pull request? Please always add it to every commit you make.

**Comment by MateStrysewske** [comment]
Please use code formatting as described in our development environment setup guide and take care of the merge conflicts. I'll review the pull request afterwards.

**Comment by mouloud-mala** [comment]
Hello Maté I used the code formatting and taked care of the merge conflicts

**Comment by MateStrysewske** [comment]
Hey! There are still a lot of merge conflicts - looks like something went wrong there?

**Comment by mouloud-mala** [comment]
Hello, all the conflicts I see are linked to the September pr, as there was no travis I do not see the conflicts you are talking about

**Pull request closed without merging**
