### PR TITLE
Contact statistics

### PR DESCRIPTION
**Pull request by faatihi**
#1281

### CODE REVIEW

**Comment by faatihi** [comment]
It's left with the legend labels of the map. Review may proceed whiles I figure that out.

**Comment by MateStrysewskeSym** [comment]
@faatihi The TravisCI build failed because apparently you used Lambda expressions in the sormas-api project. Unfortunately, because the api project is also used in the Android app and Android still officially only supports Java 7, using Java 8 features is not allowed there. I'll start the review as soon as that's fixed.

**Comment by faatihi** [comment]
OK. On it

**Comment by faatihi** [comment]
@MateStrysewskeSym , it's ready

**Comment by MateStrysewskeSym** [comment]
@faatihi Thanks! I don't think I'll be able to do the review before Tuesday because Germany has holidays tomorrow and on Monday.

**Comment by faatihi** [comment]
That's ok. We're also off till Tuesday.

**Pull request closed without merging**
