### PR TITLE
#9708 - fix hibernate lazy init issues in UI module tests

### LINKED ISSUE #9708: Wire up missing facades to `BaseFacade`
### Problem Description
We have the `BaseFacade` mechanism, however, there are still facades which do not extend it. This would allow for greater consistency and less duplicated code.

### Proposed Change
Wire up:

- [x] `PersonFacade` PR: https://github.com/hzi-braunschweig/SORMAS-Project/pull/9709
- [ ]  `SampleFacade`: Figure out how we can get this deeper into the inheritance structure (i.e., `isEditAllowed` is duplicated b/c inheritance does not work out currently)
- [ ] `VisitFacade`
- [ ] `VaccinationFacade`
- [ ] `UserFacade`
- [ ] `TreatmentFacade`
- [ ] `PrescriptionFacade`
- [ ] `TaskFacade`
- [ ] `SystemEventFacade`
- [ ] `PathogenTestFacade`
- [ ] `UserRoleFacade`
- [ ] Do one last pass over `BaseFacade` and check for necessary re-declaration of methods in facades or duplicate implementations
- [ ] `GeoLocationFacade` could potentially unify `getByName`

Write architecture test to enforce that facades extend `BaseFacade` but keep an allow list for stuff like `ImportExportFacade`.

### PR DESCRIPTION
**Pull request by leventegal-she**
Fixes #9708

### CODE REVIEW

**Comment by JonasCir** [comment]
I'm not certain we should use  `hibernate.enable_lazy_load_no_trans`. I did a quick search on the internet and in general this seems to be discouraged as it only fixes the symptoms not the root cause and has some quite negative effects on performance.

**Comment by leventegal-she** [comment]
> I'm not certain we should use `hibernate.enable_lazy_load_no_trans`. I did a quick search on the internet and in general this seems to be discouraged as it only fixes the symptoms not the root cause and has some quite negative effects on performance.
> 
> Maybe @MartinWahnschaffe or @HolgerReiseVSys have more insights.

It is set only for the tests. The issue happens only for the tests, it could be something because of the beantest library.
I don't see any other solution to make the tests run.

**Comment by StefanKock** [comment]
Failing tests on CI:
> [de.symeda.sormas.ui.caze.importer.CaseImporterTest.testImportAddressTypes](https://jenkins.sormas.netzlink.com/job/sormas-Build/de.symeda.sormas$sormas-ui/1360/testReport/junit/de.symeda.sormas.ui.caze.importer/CaseImporterTest/testImportAddressTypes/)
    [de.symeda.sormas.ui.caze.importer.CaseImporterTest.testImportAllCases](https://jenkins.sormas.netzlink.com/job/sormas-Build/de.symeda.sormas$sormas-ui/1360/testReport/junit/de.symeda.sormas.ui.caze.importer/CaseImporterTest/testImportAllCases/)
    [de.symeda.sormas.ui.contact.importer.ContactImporterTest.testImportCaseContactsDifferentAddressTypes](https://jenkins.sormas.netzlink.com/job/sormas-Build/de.symeda.sormas$sormas-ui/1360/testReport/junit/de.symeda.sormas.ui.contact.importer/ContactImporterTest/testImportCaseContactsDifferentAddressTypes/)
    [de.symeda.sormas.ui.contact.importer.ContactImporterTest.testImportCaseContacts](https://jenkins.sormas.netzlink.com/job/sormas-Build/de.symeda.sormas$sormas-ui/1360/testReport/junit/de.symeda.sormas.ui.contact.importer/ContactImporterTest/testImportCaseContacts/)
    [de.symeda.sormas.ui.event.eventparticipantimporter.EventParticipantImporterTest.testImportEventParticipantSimilarityPick](https://jenkins.sormas.netzlink.com/job/sormas-Build/de.symeda.sormas$sormas-ui/1360/testReport/junit/de.symeda.sormas.ui.event.eventparticipantimporter/EventParticipantImporterTest/testImportEventParticipantSimilarityPick/)
    [de.symeda.sormas.ui.event.eventparticipantimporter.EventParticipantImporterTest.testImportEventParticipantSimilarityPickEventParticipant](https://jenkins.sormas.netzlink.com/job/sormas-Build/de.symeda.sormas$sormas-ui/1360/testReport/junit/de.symeda.sormas.ui.event.eventparticipantimporter/EventParticipantImporterTest/testImportEventParticipantSimilarityPickEventParticipant/)
    [de.symeda.sormas.ui.importexport.ImportExportTest.testImportExportedContact](https://jenkins.sormas.netzlink.com/job/sormas-Build/de.symeda.sormas$sormas-ui/1360/testReport/junit/de.symeda.sormas.ui.importexport/ImportExportTest/testImportExportedContact/)
    [de.symeda.sormas.ui.importexport.ImportExportTest.testImportExportedCase](https://jenkins.sormas.netzlink.com/job/sormas-Build/de.symeda.sormas$sormas-ui/1360/testReport/junit/de.symeda.sormas.ui.importexport/ImportExportTest/testImportExportedCase/)

I don't get why these tests fail now. They don't fail when I run them in my IDE.

**Comment by leventegal-she** [comment]
> I don't get why these tests fail now. They don't fail when I run them in my IDE.

For me they fail when running in IDE

**Comment by MartinWahnschaffe** [comment]
> I'm not certain we should use `hibernate.enable_lazy_load_no_trans`. I did a quick search on the internet and in general this seems to be discouraged as it only fixes the symptoms not the root cause and has some quite negative effects on performance.
> 
> Maybe @MartinWahnschaffe or @HolgerReiseVSys have more insights.

Agreed. Unit tests are already quite compromised and having another setting different from production, does not help.

It looks like weld is somehow using two separate instantiations on this. Reverting the changes from https://github.com/hzi-braunschweig/SORMAS-Project/commit/3aa70293962c6c7a7e95d685b38370835818127d should help to make this work again.

Unfortunately this will bring us back to this problem: https://github.com/hzi-braunschweig/SORMAS-Project/issues/9708#issuecomment-1240621263

**Comment by MartinWahnschaffe** [comment]
Stack trace of failing unit test

> org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: de.symeda.sormas.backend.person.Person.addresses, could not initialize proxy - no Session
> 
> 	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:612)
> 	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:218)
> 	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:591)
> 	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:149)
> 	at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:188)
> 	at de.symeda.sormas.backend.person.PersonFacadeEjb.toPersonDto(PersonFacadeEjb.java:940)
> 	at de.symeda.sormas.backend.person.PersonFacadeEjb.toDto(PersonFacadeEjb.java:885)
> 	at de.symeda.sormas.backend.person.PersonFacadeEjb$PersonFacadeEjbLocal$Proxy$_$$_WeldSubclass.toDto(Unknown Source)
> 	at de.symeda.sormas.backend.person.PersonFacadeEjb.convertToDto(PersonFacadeEjb.java:1534)
> 	at de.symeda.sormas.backend.person.PersonFacadeEjb$PersonFacadeEjbLocal$Proxy$_$$_WeldSubclass.convertToDto(Unknown Source)
> 	at de.symeda.sormas.backend.person.PersonFacadeEjb.lambda$getByUuid$2(PersonFacadeEjb.java:319)
> 	at java.base/java.util.Optional.map(Optional.java:265)
> 	at de.symeda.sormas.backend.person.PersonFacadeEjb.getByUuid(PersonFacadeEjb.java:319)
> 	at de.symeda.sormas.backend.person.PersonFacadeEjb$PersonFacadeEjbLocal.getByUuid(PersonFacadeEjb.java:1778)
> 	at de.symeda.sormas.backend.person.PersonFacadeEjb$PersonFacadeEjbLocal$Proxy$_$$_WeldSubclass.getByUuid(Unknown Source)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.jboss.weld.interceptor.proxy.SimpleInterceptionChain.interceptorChainCompleted(SimpleInterceptionChain.java:52)
> 	at org.jboss.weld.interceptor.chain.AbstractInterceptionChain.invokeNextInterceptor(AbstractInterceptionChain.java:83)
> 	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:48)
> 	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:41)
> 	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:53)
> 	at de.symeda.sormas.backend.person.PersonFacadeEjb$PersonFacadeEjbLocal$Proxy$_$$_WeldSubclass.getByUuid(Unknown Source)
> 	at de.symeda.sormas.backend.person.PersonFacadeEjb$PersonFacadeEjbLocal$Proxy$_$$_WeldClientProxy.getByUuid(Unknown Source)
> 	at de.symeda.sormas.ui.caze.importer.CaseImporterTest.testImportAddressTypes(CaseImporterTest.java:353)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> 	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:55)
> 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
> 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
> 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
> 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
> 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
> 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
> 	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
> 	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
> 	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:41)
> 	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
> 	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
> 	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
> 	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
> 	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
> 	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
>

**Review by StefanKock — APPROVED** [review]

**Pull request merged**
