### PR TITLE
#3360 REST] handle missing UUID in EntityDTOs gracefully

### PR DESCRIPTION
**Pull request by leventegal-she**
Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/3360

### CODE REVIEW

**Review by JonasCir — CHANGES_REQUESTED** [review]
Hi looks good to me. Just minor remarks:

- [ ] SormasToSormasFacadeEjb line 628 should also be changed

- [x] VisitFaceEjb line 495 should be changed 

Further, I assume that tests which assert that creations with uuid provided works are present?

- [ ] also EpiDataFacade line 86

**Comment by JonasCir** [comment]
@leventegal-she Can you address the changes? :)

**Comment by leventegal-she** [comment]
VisitFaceEjb and EpiDataFacade done

SormasToSormasFacadeEjb not needed because it's only creation and there is no dto used

**Review by JonasCir — APPROVED** [review]
lgtm thanks!

**Pull request merged**
