### PR TITLE
Feature 3488 lab message UI first approach

### PR DESCRIPTION
**Pull request by ChristopherRiedel**
#3488

### CODE REVIEW

**Comment by FredrikSchaeferVitagroup** [comment]
There seems to be a small issue with screens of some aspcect ratios less extreme than ultrawide. When processing a lab message, while viewing the labmessage as HTML on the left, and some form on the right, there is a small overlap in the middle.

**Comment by FredrikSchaeferVitagroup** [comment]
There is another small issue when creating a sample while processing: all required fields are marked red, except the RESULTS VERIFIED BY LAB SUPERVISOR. This is a little irritating.

**Comment by FredrikSchaeferVitagroup** [comment]
When processing, the pathogenTestResult is always set to PENDING by default. Is that desired behaviour?

**Review by sergiupacurariu — COMMENTED** [review]
on Creating new sample, "Date sample was collected" remains with red borders even after the dates were corrected but save works

**Review by FredrikSchaeferVitagroup — CHANGES_REQUESTED** [review]

**Review by FredrikSchaeferVitagroup — APPROVED** [review]

**Review by sergiupacurariu — APPROVED** [review]

**Pull request merged**
