### PR TITLE
[IMIS] Local dev setup using maven-cargo (fixes #2695)

### LINKED ISSUE #2695: [IMIS] Local dev setup using maven-cargo
### Feature Description
Setup of a local development
 server using maven-cargo-plugin. Setup is reduced to two steps:
- docker-compose up (database
 setup using the docker image)
- mvn cargo:run (install
 payara server, deploy artifacts start server)
The
 implementation of this task includes the integration of serverlib dependency artifacts in the maven build process, generating a dependency jar as well as a zip artifact.

### PR DESCRIPTION
**Pull request by syntakker**
Added modules:
- **sormas-serverlibs**: server dependencies, provides both zip and jar artifacts (to be discussed: integrate sormas-serverlibs zip into server setup to avoid code duplication of `sormas-base/dependencies/serverlibs.pom`)
- **sormas-devserver**: local dev server setup using maven-cargo

### CODE REVIEW

**Comment by syntakker** [comment]
The definition of Travis lifecycle phases prior to commit `515a82b` executes `mvn test -B ...` as defined for the `install` phase, followed by an execution of another `mvn test -B` from Travis' default `script` phase. Thus
- `mvn install ...` is never executed, i.e., the maven lifecycle phases `package` and `install` are not covered by a Travis run
- `mvn test -B ...` is executed twice, which substantially increases the time of a Travis run

The Travis log reads (e.g., https://travis-ci.org/github/hzi-braunschweig/SORMAS-Project/builds/721680110):
```
$ mvn test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn (install) (726.43s)
$ mvn test -B (537.68s)
```

By skipping instead Travis' `install` phase and have `mvn install ...` executed in the `script` phase, Travis runs a complete maven install covering maven's lifecycle phases `test` - as before - as well as `package` and `install`. Now the Travis log reads (https://travis-ci.org/github/hzi-braunschweig/SORMAS-Project/builds/721954371):
```
Skipping the install step, as specified in the configuration.
$ mvn install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn (803.49s)
```

The elapsed time for the Travis run is reduced from 21 min 27 sec in the above example to 13 min 48 sec in the latter run.

**Comment by MartinWahnschaffeSymeda** [comment]
@syntakker Thanks a lot for the PR!

Starting with a general comment first: The dev/server setup of SORMAS is currently quite messy and needs to be streamlined (PR #2375 will improve that quite a bit). We have the SERVER_SETUP, the SERVER_DEV_SETUP and also the SORMAS-Docker Project. All of this comes with some redundancy (see #2427), so we are a bit hesitant when it comes to adding even more. 

On the other side the approach you have chosen here makes it really easy to quickly start a server to do some testing and development, so we should definitely go for it and have it here as an alternative way.

In detail @StefanKock and I have a few change requests:

- [ ] Since the domain.xml is completely checked in, it's difficult to change the ports. Especially the postgres 5432 is likely to interfere with an existing postgres server on the local system. Either the port configuration needs to be done in another way (e.g. providing the port in an .env file and setting up the database connections with script commands) or we should at least use a different port here (e.g. 5434).
- [ ] Instead of creating a new module for the serverlibs, please use the existing pom in sormas-base/dependencies. The artifact xml files can also be moved there.
- [ ] There are several placeholder.txt files, for this please use the .gitkeep files instead
- [ ] Please change the name of the devserver module to something like quickstart/quickserver (or hopefully you come up with something better). The reason for this request is, that there will be two ways for developers to setup their local server. The solution provided here will be a quick start for people who want to contribute to a few issues. For mid- and long-term developers the "setup" way will for now stay the default, because it's faster to startup, allows easy full customization and a permanent database (the postgres database here will be lost when a mvn clean is done - which is perfect for this use case).
  #2375 is improving the workflow for the dev server to make that 
- [ ] Postgres docker version 2.7.2 does not seem to exist

**Comment by syntakker** [comment]
@MartinWahnschaffeSymeda the requested changes are implemented:

- Cargo server configuration: the database port is configurable, so the server can connect against an existing (permanent) database now. I could also abstract the database host to connect against a remote database, if there is a use case for that. Configuration is done via the `.env` file an described in the `README.md`. The setup does not change, the configurations in `.env` are used for both running the docker image and filtering the `domain.xml` file.
- Serverlibs: I've moved the assembly to the existing `sormas-base/dependencies` module. However, to me both the location of the module (it is the only module not in the toplevel directory) and the naming of the pom seem slightly unnatural (it is not possible to `cd` into the directory and run `mvn install`). The zip assembly is unused for now, but it could replace the ant script to extract the serverlibs. This way the serverlibs are a proper artifact and can be distributed via the maven repository.

**Comment by syntakker** [comment]
For the serverlibs: to avoid any code duplication at all, it might also be possible to extract dependencies with scope `provided` from the deployed artifacts, i.e., `sormas-ear`, `sormas-rest` and `sormas-ui`. I can have a look at this, if this is of interest.

**Comment by syntakker** [comment]
@MartinWahnschaffeSymeda As discussed, I have added some configurability. Additional properties can be defined by adding a file `custom.env` (for docker-compose and domain.xml configuration) and/or `custom.properties` (to be merged in `sormas.properties`), see `sormas-cargoserver/README.md`.
We have also set the tag `latest` for the `sormas-postgres` docker image.

**Comment by MartinWahnschaffeSymeda** [comment]
@syntakker Looks great! 

Shouldn't the custom example files be located in the cargo root directory instead of the target subdirectory, though? At least it works fine for me to have a custom env in the module root (sormas-cargoserver).

Also I'd still suggest to use 5434 as the default port. It would make a conflict with an existing postgres installation by default less likely and from my understanding it would not have any negative side-effects.

**Comment by syntakker** [comment]
Yes, example files in the target folder was by mistake :-)
Default postgres port is now changed to 5434.

**Pull request merged**
