### PR TITLE
[#7507] add dependabot config

### LINKED ISSUE #7507: Enable automatic dependabot PRs [1]
### Problem Description

Right now, we are managing our dependencies manually which is slow, error prone, and bears unnecessary risks. 

### Proposed Solution

 - Provide `dependabot.yml` to configure automated updates.
 - Define artifacts to ignore: vaadin dependencies

### Possible Alternatives

Keep clustering dependency updates in bigger tickets and lesser steps to keep stack tested at that point.

### Additional Information

Wait for #11032 and #10499 to be merged to have a clean baseline.

### PR DESCRIPTION
**Pull request by JonasCir**
Fixes #7507 
Take a look at my private fork's PR [queue](https://github.com/JonasCir/SORMAS-Project/pulls): The amount of PR this bot creates is manageable.

### CODE REVIEW

**Review by MateStrysewske — APPROVED** [review]

**Comment by MateStrysewske** [comment]
@JonasCir Also requested a review from @StefanKock

**Review by StefanKock — CHANGES_REQUESTED** [review]
1. Since sormas-base is aggregated most dependencies by pattern, all directly listed Maven modules should not be listed (will probably result in duplicates?).
2. `sormas-app` is also a gradle project, and most dependencies are managed there (technically independent from Maven).
3. `sormas-e2e-performance-tests` and `sormas-e2e-tests` are no maven projects

In general, I don't see that version updates should be done automatically.

**Comment by JonasCir** [comment]
Hi thanks for the remarks!
1. Dependabot does not duplicate updates and understands our structure. I admit `Maven` is a little bit of a misnomer. Read [here](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates): " Dependabot doesn't run Maven but supports updates to pom.xml files". So all the paths in the file explicitly point the bot to our poms, it really does no harm.
2. True but it has a pom in the directory, see 1. It does no harm. Gradle support will need some minor refactoring which I can't do right now, will be enabled later.
3. True, removed it temporarily until I get gradle to work later.

The bot will only provide the PRs for us to merge. I think that getting away from manually tracking dependencies to an more automated approach is highly beneficial.

Also the following an more can be configured: commit message, source branch, reviewers, labels, etc see [here](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates). Let me now if you want to have something specific here.

**Comment by StefanKock** [comment]
Well for start: Changing anything on the software shall be documented in ticket, and the commit has to be linked to the ticket. How does this come into this automation approach.

**Comment by JonasCir** [comment]
Your right, this makes perfectly sense for humans, but I think it is fine to make an exception for a bot which does nothing else than, well, provide PRs which bumps a version number in a POM with an already clear and _distinct_ commit message. 

Referencing a tracking issue from the bot  would just repeatedly fill the tracking issue with related commits. I don't see how looking at an ever extending and overflowing issue helps anyone. Also leaving the issue number out for the automatic commits would clearly highlight which parts of the pom were modified by humans if you inspect the git history.

In case we really want to introduce this, you can check out this [link](https://github.com/JonasCir/SORMAS-Project/pull/6/commits) from my fork which contains commits that adhere to the scheme you asked for :rocket:. Turns out `dependabot` is quite flexible and it also will receive new features in the future which are likely to contribute even more to a healthy, stable, and secure product.

**Comment by JonasCir** [comment]
If there are further concerns, I'm happy to discuss them tomorrow in our meeting.

**Comment by JonasCir** [comment]
Branch is broken I start from scratch.

**Pull request closed without merging**
