### PR TITLE
[#9708] wire up persons to BaseFacade

### PR DESCRIPTION
**Pull request by JonasCir**
Ticks one box (i.e., `PersonFacade`) of #9708 

While I was waiting for news about the current S2S crisis, I decided to do something useful and conducted some code gardening :farmer:

### CODE REVIEW

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
There are quite a lot failing tests that I'd like to see fixed before I do an in-depth review of this :)

**Comment by JonasCir** [comment]
rebased and test fixed

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
Server does not start for me with the following message:

A method overriding another method must not redefine the parameter constraint configuration, but method PersonFacadeEjb#save(PersonDto) redefines the configuration of BaseFacade#save(EntityDto).

**Comment by JonasCir** [comment]
Ah, one annotation was wrong, starts now :)

**Review by MateStrysewske — APPROVED** [review]

**Pull request merged**
