### PR TITLE
[#7542] add sonar cloud CI pass

### LINKED ISSUE #7542: Add `trivy` and `sonar` repo scan to GitHub actions [3]
### Problem Description
We are currently using CodeQL to scan for security problems integrated into Github and sonarqube to do a more detailed scan which also includes CVE vulnerabilities. Unfortunately sonarqube is not integrated into the pull request mechanics so it's easy to miss new vulnerabilities.

### Proposed Change
- Use trivy to check for vulnerabilities (most importantly CVE https://avd.aquasec.com/). This should be integrated into the checks executed for pull requests.
- Include current rules from SonarQube and let these rules evaluate new code in a pull request (for now don't block the pull request).

### Acceptance Criteria
* Warnings for existing problems are shown as security alerts on Github
* Vulnerabilities in pull requests are shown as part of the checks.

### Alternatives
Use sonarcloud: https://sonarcloud.io/github

### PR DESCRIPTION
**Pull request by JonasCir**
Fixes #7542

### CODE REVIEW

**Comment by JonasCir** [comment]
@MartinWahnschaffe 
I guess (hope) we can configure rules like described [here](https://www.baeldung.com/sonar-exclude-violations), however, I cannot really test it right now. 

My current proposal would be to merge this to get a baseline and then conduct further tests.

**Comment by MartinWahnschaffe** [comment]
Guess you are referring to the properties file? https://www.baeldung.com/sonar-exclude-violations#using-sonar-projectproperties

Can we extract the one we have and already include it in this PR?

Besides that I'd say: Let's have a try and see what happens.

**Comment by sormas-vitagroup** [comment]
Thanks for reporting!

**Comment by sormas-vitagroup** [comment]
ANALYSIS SUCCESSFUL, you can find the results at: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11387

**Comment by MartinWahnschaffe** [comment]
@JonasCir Instead of "ANALYSIS SUCCESSFUL, you can find the results at ..." use "sonarcloud analysis: ..."
"Successful" is misleading, because the quality gate may still have failed.

**Comment by sormas-vitagroup** [comment]
ANALYSIS SUCCESSFUL, you can find the results at: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11387

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: Please find the results at https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11387

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: please find the results at https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11387

**Comment by JonasCir** [comment]
@MartinWahnschaffe: I think this can be merged?

**Review by MartinWahnschaffe — APPROVED** [review]

**Pull request merged**
