### PR TITLE
#11557 - edit child should be depending on parent and child edit rights

### LINKED ISSUE #11557: Make child entities deletable for users with the delete but without the accompanying edit right [5]
### Problem Description

Ticket #11509 introduces the following behavior: users that have delete rights but no edit rights over entities can now click the 'Delete' button.

The following child entities are not covered:
- [x] Prescription
- [x] Treatment 
- [x] Follow-up  
- [x] Clinical course  
- [x] Pathogen Test  

### Proposed Change

Enable the 'Delete' button for the child entities mentioned in the 'Problem description' if the user has the respective delete right, even if they don't have the edit right for the child entity or its parent entity, as long as the entity is in the user's jurisdiction.

### Acceptance Criteria

- a user should be able to delete the child entities for which they have deletion right but no edit right;
- the parent entity needs to be within the users jurisdiction for the user to be able to delete the parent entity or the child entity (jurisdiction based on disease and on responsible region and district).

### Added value/Benefit
Consistency across the app in what concerns the possibility to delete entities over which the user does not have edit right, but has delete right.

### Additional Information

Note: The changes for the Android app will be handled in a separate story: https://github.com/hzi-braunschweig/SORMAS-Project/issues/11892

### PR DESCRIPTION
**Pull request by carina29**
Fixes #11557

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11952

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11952

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11952

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11952

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11952

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11952

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11952

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11952

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11952

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11952

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11952

**Comment by carina29** [comment]
@MateStrysewske , @sergiupacurariu In https://github.com/hzi-braunschweig/SORMAS-Project/issues/11557 in one of the comments was also requested the correct display of the headings view/edit. Some changes from my first PR attached to this feature introduced a bug in the correct display of the buttons ( delete, edit, discard) based on the rights. I've corrected this problem also in this second PR attached to 11557.

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11952

**Review by sergiupacurariu — APPROVED** [review]

**Pull request merged**
