### PR TITLE
3409 prohibition to work fields

### LINKED ISSUE #3409: SurvNet Adaptations - Create new field “Prohibition to work” for case and contact
### Feature Description

Create new field “Prohibition to work” for case and contact

Contacts > Open contact information
Cases > Open case information

New fields (only DE)-
” Tätigkeitsverbot” (de-de) | “Prohibition to work” (en) [SurvNet field name: ProhibitionOfOccupation, ProhibitionOfOccupationfromDate; ProhibitionOfOccupationUntilDate]

Next to or under the existing field "Einrichtung" (de-de) | “Facility” (en)

Data Type: Dropdown/enum
Values (de-de) | (en)
• -nicht erhoben- | data not collected
• -nicht ermittelbar- | unknown
• Ja | yes
• Nein | no

### PR DESCRIPTION
**Pull request by leventegal-she**
Closes #3409

### CODE REVIEW

**Comment by vlad-ciucescu** [comment]
I can add an interdiction to work end date in the future, and it will be marked as invalid in the UI, but I can actually save the contact successfully.
image

**Comment by leventegal-she** [comment]
> I can add an interdiction to work end date in the future, and it will be marked as invalid in the UI, but I can actually save the contact successfully.
> image
> 
> This happens only for contacts, for cases the validation seems to be done properly.

I couldn't reproduce this issue. On the screenshot the dates are ok the from date is october and the until date is december, that's why you were able to save the contact. 
The red border is probably a styling issue, could you please create a new bug ticket with the exact steps to reproduce.

**Comment by vlad-ciucescu** [comment]
> 
> 
> > I can add an interdiction to work end date in the future, and it will be marked as invalid in the UI, but I can actually save the contact successfully.
> > image
> > This happens only for contacts, for cases the validation seems to be done properly.
> 
> I couldn't reproduce this issue. On the screenshot the dates are ok the from date is october and the until date is december, that's why you were able to save the contact.
> The red border is probably a styling issue, could you please create a new bug ticket with the exact steps to reproduce.

In this case I was confused, I thought that both dates must be in the past. It is just a styling issue then.

**Comment by leventegal-she** [comment]
> In this case I was confused, I thought that both dates must be in the past. It is just a styling issue then.

I found the issue and fixed it

**Review by vlad-ciucescu — APPROVED** [review]

**Pull request merged**
