### PR TITLE
#8540 Add backend checks for Sormas2Sormas

### LINKED ISSUE #8540: Add backend checks for Sormas2Sormas [5]
### Problem Description
We are missing checks for many of the user rights related to accessing the backend. 

### Proposed Change
We need to check user rights need to access the facade below and their methods. 

The following facades are very closely related and need to check whether the user has the S2S_SHARE user right and the EDIT user right for the respective entity (overrride the share method to add the needed RightsAllowed annotation).
Within the share method check whether other entities are included and whether the user has the needed user right for those.

- [x] AbstractSormasToSormasInterface
- [x] SormasToSormasCaseFacadeEjb
- [x] SormasToSormasContactFacadeEjb
- [x] SormasToSormasEventFacadeEjb
- [x] SormasToSormasLabMessageFacadeEjb

This also needs to be checked in the user interface for the sharing of

- [x] case(s)
- [x] contact(s)
- [x] event(s)
- [x] external message(s)

Furthermore:

- [x] SormasToSormasShareInfoFacadeEjb, SormasToSormasShareRequestFacadeEjb, SormasToSormasOriginInfoFacadeEjb: check S2S_SHARE and S2S_CLIENT user rights when creating/editing share meta objects. We don't have a dedicated user right to right share meta data and probably also don't need it.
- [x] SormasToSormasFacadeEjb: Add checks for S2S_SHARE and S2S_CLIENT
- [x] Check usage of these facades in the StartupShutdownService and CronService and make sure called facade methods are annotated with RightsAllowed including UserRight._SYSTEM.
- [x] Extend the archunit test implemented by #8508

### PR DESCRIPTION
**Pull request by leventegal-she**
Fixes #8540

### CODE REVIEW

**Comment by JonasCir** [comment]
@leventegal-she 
Nicely done! :+1: 
please resolve the conflict and I'm going to approve this

**Review by JonasCir — APPROVED** [review]
lgtm

**Comment by JonasCir** [comment]
@leventegal-she You certain, that you do not want to merge this? :D

**Comment by leventegal-she** [comment]
The release is not yet done and this is not part of the commitment so I can't merge yet

**Pull request merged**
