### PR TITLE
[#7507] Add dependabot config for GH Actions

### PR DESCRIPTION
**Pull request by JonasCir**
Fixes https://github.com/hzi-braunschweig/SORMAS-Project/issues/11676

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11657

**Review by MartinWahnschaffe — APPROVED** [review]

**Comment by MartinWahnschaffe** [comment]
Please create a new issue within epic #7503 for this

**Comment by JonasCir** [comment]
Done

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11657

**Pull request merged**
