### PR TITLE
#9595 - Fix crashes on Android 12

### LINKED ISSUE #9558: Mobile App v1.72.1 crashes when opened
### Bug Description
The mobile app (v1.72.1) crashes when opened. Sometimes it displays a message to clear the cache because it has a bug but still crashes afterwards. Sometimes it displays the message that the app has a bug.

### Steps to Reproduce
1. Download latest release ZIP file for 1.72.1
2. Install APK (from either release or debug folders in ZIP file) on mobile phone
3. Open app

### System Details

* Device: Samsung Galaxy A52
* SORMAS version: 1.72.1
* Android version: 12
* Server URL:
* User Role:

### PR DESCRIPTION
**Pull request by MateStrysewske**
Fixes #9558

### CODE REVIEW

**Review by sergiupacurariu — APPROVED** [review]

**Comment by BasilKaburi** [comment]
@MateStrysewske @sergiupacurariu 
Unfortunately, the app crashed twice in the last hour. (version 1.72.2 on android version 11).
Screenshot_20220629-131602_APMIS

**Comment by BasilKaburi** [comment]
@zohaibhassan122 @bernardsilenou  FYI

**Comment by MateStrysewske** [comment]
@BasilKaburi Crashes during the usage of SORMAS are not directly related to the issue linked to this pull request, it's about the app crashing directly upon being opened.

**Comment by BasilKaburi** [comment]
@MateStrysewske Please,  I'm confused here and need some clarifications:
1. What was fixed in this issue?
2. How was it (or should it be)  tested?
3. What is the difference between this issue and #9436?
I guess whichever way the app crashes, it is not ok.

**Comment by BasilKaburi** [comment]
@zohaibhassan122 @bernardsilenou FYI

**Comment by MateStrysewske** [comment]
@BasilKaburi The issue linked to this pull request is about the app crashing immediately after opening on Android 12.

**Pull request merged**
