### PR TITLE
[#7542] introduce trivy repo scanner

### LINKED ISSUE #7542: Add `trivy` and `sonar` repo scan to GitHub actions [3]
### Problem Description
We are currently using CodeQL to scan for security problems integrated into Github and sonarqube to do a more detailed scan which also includes CVE vulnerabilities. Unfortunately sonarqube is not integrated into the pull request mechanics so it's easy to miss new vulnerabilities.

### Proposed Change
- Use trivy to check for vulnerabilities (most importantly CVE https://avd.aquasec.com/). This should be integrated into the checks executed for pull requests.
- Include current rules from SonarQube and let these rules evaluate new code in a pull request (for now don't block the pull request).

### Acceptance Criteria
* Warnings for existing problems are shown as security alerts on Github
* Vulnerabilities in pull requests are shown as part of the checks.

### Alternatives
Use sonarcloud: https://sonarcloud.io/github

### PR DESCRIPTION
**Pull request by JonasCir**
Fixes #7542

This introduces the [trivy](https://aquasecurity.github.io/trivy/dev/) security scanner which we let operate in its repo/filesystem scan mode. It scan everything in the repo from the poms up to shipped jars we include as server dependencies. 

I have to say I'm quite impressed by this tool. 

---

We can skip this until keycloak and payara are updated.

### CODE REVIEW

**Comment by JonasCir** [comment]
Note to self 27/12 on last run

**Comment by MartinWahnschaffe** [comment]
Nice!
If I get this right, it doesn't prevent PRs from being merged, it just raises a red flag in the PR and in the security section, right?

**Comment by JonasCir** [comment]
Correct, as you can see in the box, the corresponding CI job will fail and it will report findings to the security tab (if run on development)

**Comment by StefanKock** [comment]
I'm against merging something where the epic and ticket were not discussed/refined first.

**Pull request closed without merging**
