### PR TITLE
Change/11191 update workflows

### LINKED ISSUE #11191: Fix the current GitHub Actions warnings [2]
### Problem Description

Most of the the GitHub Action workflows produce deprecation warnings indicating that certain features wont work in the future. In order to ensure build stability, we should address them.

Fix the warnings shown here:
* gradle app CI: https://github.com/hzi-braunschweig/SORMAS-Project/actions/runs/3703589177
* maven CI: https://github.com/hzi-braunschweig/SORMAS-Project/actions/runs/3703555423
* linter: https://github.com/hzi-braunschweig/SORMAS-Project/actions/runs/3703711134
* openapi canary: https://github.com/hzi-braunschweig/SORMAS-Project/actions/runs/3681859055
* gradle wrapper: https://github.com/hzi-braunschweig/SORMAS-Project/actions/runs/3703869940

### Proposed Change

- Update Github Action versions

### Acceptance Criteria

No more warnings in our workflows which indicate a potential breakage in the future. 

### Implementation Details

Mostly bump action versions I guess...

### PR DESCRIPTION
**Pull request by JonasCir**
Fixes #11191 

~~Merge after #11644 and #11640~~ Done

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11196

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11196

**Review by StefanKock — APPROVED** [review]
Code Review: I don't have any objections, but not deep knowledge of the tooling.

I suggest to squash the commit history while/before merging. It does not look beneficial to keep so much small changes in the history.

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11196

**Pull request merged**
