### PR TITLE
Feature missing fields for meningitis

### PR DESCRIPTION
**Pull request by faatihi**
#982

### CODE REVIEW

**Comment by MateStrysewskeSym** [comment]
I don't have any improvement suggestions for this pull request. I suggest we leave it open until #1291 has been completed though because these new fields need to be added to the app as well.

**Comment by faatihi** [comment]
OK. Can I go ahead and work on the app as well, using this same branch? We can tag the issue with sormas-app.

**Comment by MateStrysewskeSym** [comment]
@faatihi I'd be hesitant about merging the bed-side lab testing pull request with this one because you might run into some not-so-enjoyable conflicts. I suggest to rather wait until #1291 is ready and concentrate on implementing the new diseases in the meantime, but you're free to do as you wish. ;)

**Comment by faatihi** [comment]
Alright. I'll wait then. :)

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi The backend and web looks good and should work fine.
With the app now having the ability to create and edit pathogen tests I need you to add those new fields (serotype, cqValue) to the app PathogenTest, fragements and database as-well.

**Comment by faatihi** [comment]
this request is ready for review

**Pull request merged**
