### PR TITLE
SORQA-887 Stabilize "Test Permanent deletion for Person for Event Par…

### PR DESCRIPTION
**Pull request by hms-sgent**
…ticipant". An dditional step has been added to click on the event participant tab.

Fixes #

### CODE REVIEW

**Comment by hms-sgent** [comment]
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/2584/allure/#suites/ba64af4344a5d1b16948f67eae90e934/2699ce932ebd16bb/

**Comment by hms-sgent** [comment]
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/2584/allure/#suites/ba64af4344a5d1b16948f67eae90e934/2699ce932ebd16bb/

**Comment by hms-sgent** [comment]
image

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11745

**Pull request merged**
