### PR TITLE
#11886 [S2S] The sync between target instance and source instance is …

### LINKED ISSUE #11886: [S2S] The sync between target instance and  source instance is broken when was handed over
### Problem Description

After sharing case with the sample I can change the "date of sample collection" in the target instance and the updated date should be shown in the source instance but it doesn't (remains the old date of collection).
Obs: The same problem appears also for  Vaccination, Surveillance reports, Person

### Reproduction Steps

1. Login as a Admin user on the source instance (https://test-de1.sormas.netzlink.com)
2. Create a case with sample
3. Share case with hand over the ownership to the target instance (https://test-de2.sormas.netzlink.com)
4. Accept the case in target instance
5. Go to the shared case in target instance and edit the sample collection date
6. Save and go to the source instance
7. Check in the case if sample collection date is updated
 -> sample collection date in the source instance is not updated
...

### Expected Behavior

The sample collection date in the source instance should be updated.

### Affected Area(s)

Web app

### SORMAS Version

Version: 1.83.0-SNAPSHOT (561c5a3)

### Android version/Browser

Chrome

### User Role(s)

Admin

### Server URL

https://test-de1.sormas.netzlink.com and https://test-de2.sormas.netzlink.com

### Additional Information

_No response_
[S2S-syncDateSampleError.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/11295764/S2S-syncDateSampleError.txt)

### PR DESCRIPTION
**Pull request by leventegal-she**
Fixes #11886

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11945

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11945

**Comment by carina29** [comment]
@ChristopherRiedel  @leventegal-she I'm not sure if this bug appeared due to the fact that the @NotNull annotation was added to the labUser and was mandatory to be defined , but if yes, Martin created a new story (already merged on hotfix-1.83.1) to remove the @NotNull annotation from the labUser field. 
Was this bug retested on hotfix-1.83.1 after Martin removed the @NotNull annotation?

https://github.com/hzi-braunschweig/SORMAS-Project/issues/11922

**Comment by leventegal-she** [comment]
@carina29 It is due to that annotation

Retested it and it's working on the latest hotfix-1.83.1, so there is no need for this fix

**Review by ChristopherRiedel — COMMENTED** [review]
Please move the fix to development

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11945

**Pull request closed without merging**
