### PR TITLE
qu-auto/SORQA-836 Automatize "[4106] Improve the mapping/prefilling the new case/new sample forms when processing a DEMIS LabMessage"

### PR DESCRIPTION
**Pull request by hms-sgent**
Fixes #

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11506

**Comment by hms-sgent** [comment]
image

**Comment by hms-sgent** [comment]
image

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11506

**Pull request merged**
