### PR TITLE
#1865 App feature - automatic location picking

### PR DESCRIPTION
**Pull request by opatajoshua**
Automatically pick current location coordinates when creating case and contact
app should initially set current address when person address is null
save a contact person's address to current location after follow up

### CODE REVIEW

**Comment by faatihi** [comment]
#1865

**Comment by bernardsilenou** [comment]
@faatihi The address of the person is not always where the case is being created. Picking the gps address when a case is created is not prone to errors? How does this work please?

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou I'm also not a fan of this change. However, it's a request from Ghana. I suggest to discuss this in the review next week.

**Comment by opatajoshua** [comment]
> In this state, the feature doesn't make sense to me. First of all, the address location right now is always overridden, even if it is already set, which means that during every change, the potentially correct person address is removed. There needs to be a check whether the person address already has GPS coordinates. Secondly, the code to set the person address should not be executed in the fragment, especially not in a binding method. It's fine to do this during a save, but it should then be done when saving a NEW case, contact or visit, not when saving an existing one because it's extremely likely that those aren't done where the person actually lives.

Will make the necessary changes and submit

**Comment by MateStrysewskeSym** [comment]
@opatajoshua Alright, thanks!

**Comment by bernardsilenou** [comment]
@opatajoshua It is not a good practice to implement automatic pecking of coordinates for cases or contacts. I know this is requested but implementing it this way will affect the epidemiology behind the special spread of the diseases on the map. I commented on #1865  on  how to walk around it.

**Pull request closed without merging**
